// mlp_params.vh is auto-generated by train_and_export.py and defines:
//   `MLP_REQ_SHIFT_FC1  — right-shift for FC1 output requantization
//   `MLP_REQ_SHIFT_FC2  — right-shift for FC2 output requantization
// Re-run train_and_export.py after retraining; then re-synthesise in Vivado.
`include "mlp_params.vh"

// =============================================================================
// mlp_engine.v
//
// Serial MLP inference engine — Zybo Z7-10
// Network : 784 → FC1(64, ReLU) → FC2(32, ReLU) → FC3(10, argmax)
// Weights : INT8, stored byte-addressable in Port B of the Param BRAM
// Biases  : INT32, stored as 4 consecutive bytes (little-endian) in Param BRAM
// Inputs  : INT8 pixels, stored byte-addressable in Port B of the Input BRAM
// MAC     : 3 cycles per multiply (ADDR → LATCH → ACC)
//           Both BRAMs configured with DO_REG=0 → 1-cycle read latency
// Output  : 4-bit predicted class (0–9), one-cycle done pulse
//
// Bias read: 4 bytes per bias neuron (INT32, little-endian):
//   S_BIAS_ADDR → S_BIAS_LATCH → S_BIAS_LOAD  (×4, byte index 0..3)
//   On byte 3: i=0, proceed to S_W_ADDR
//
// Timing at 100 MHz:
//   FC1: 64 × (8 + 784×3) ≈ 150 848 cycles
//   FC2: 32 × (8 +  64×3) ≈   6 272 cycles
//   FC3: 10 × (8 +  32×3) ≈   1 040 cycles
//   Total ≈ 158 160 cycles ≈ 1.58 ms / inference
// =============================================================================
`timescale 1ns / 1ps

module mlp_engine #(
    // Inter-layer requantization right-shifts.
    // Sourced from `mlp_params.vh (auto-generated by train_and_export.py).
    // k = round(log2(act_scale / (w_scale * x_scale)))
    // After FC1/FC2 MAC:  act_int8 = clip(ReLU(acc_int32 >>> k), 0, 127)
    parameter [4:0] FC1_REQ_SHIFT = `MLP_REQ_SHIFT_FC1,
    parameter [4:0] FC2_REQ_SHIFT = `MLP_REQ_SHIFT_FC2
) (
    input  wire        clk,
    input  wire        rst_n,

    // ── Control ───────────────────────────────────────────────────────────────
    input  wire        start,      // one-cycle pulse to begin inference
    output reg         done,       // one-cycle pulse when result is valid
    output reg  [3:0]  result,     // predicted class 0–9

    // ── Param BRAM — Port B (read-only, 8-bit data) ───────────────────────────
    // Weights and biases stored contiguously; see BRAM_OFFSETS below.
    output reg  [15:0] param_addr,
    output reg         param_en,
    input  wire [7:0]  param_rdata,

    // ── Input BRAM — Port B (read-only, 8-bit data) ───────────────────────────
    // 784 INT8 pixels written by the PS before asserting start.
    // The PS must normalize uint8 pixels and quantize to INT8 before writing:
    //   x_float = (pixel/255.0 - MLP_INPUT_MEAN) / MLP_INPUT_STD
    //   x_int8  = clamp(round(x_float / MLP_INPUT_SCALE), -128, 127)
    // Written as two's-complement bytes; RTL sign-extends when reading.
    output reg  [9:0]  input_addr,
    output reg         input_en,
    input  wire [7:0]  input_rdata
);

// =============================================================================
// Param BRAM byte-address map
// Must match the offsets in firmware/weights_biases.h exactly.
//
// All biases are INT32 (4 bytes each), so bias blocks are 4× larger than
// the old INT8 layout.
// =============================================================================
localparam [15:0] FC1_W_BASE = 16'h0000;  // fc1 weights  [64×784  INT8]  = 50 176 B
localparam [15:0] FC1_B_BASE = 16'hC400;  // fc1 biases   [64      INT32] =    256 B
localparam [15:0] FC2_W_BASE = 16'hC500;  // fc2 weights  [32×64   INT8]  =  2 048 B
localparam [15:0] FC2_B_BASE = 16'hCD00;  // fc2 biases   [32      INT32] =    128 B
localparam [15:0] FC3_W_BASE = 16'hCD80;  // fc3 weights  [10×32   INT8]  =    320 B
localparam [15:0] FC3_B_BASE = 16'hCEC0;  // fc3 biases   [10      INT32] =     40 B

// =============================================================================
// FSM state encoding
// =============================================================================
localparam [3:0]
    S_IDLE        = 4'd0,
    S_FC_INIT     = 4'd1,   // load layer config registers, reset j
    S_BIAS_ADDR   = 4'd2,   // assert param_addr = b_row_base + bias_byte_idx
    S_BIAS_LATCH  = 4'd3,   // wait 1 cycle (BRAM latency)
    S_BIAS_LOAD   = 4'd4,   // shift param_rdata into acc[bias_byte_idx*8+:8]
                             //   byte 0..2: bias_byte_idx++, loop to S_BIAS_ADDR
                             //   byte 3:   i=0, go to S_W_ADDR
    S_W_ADDR      = 4'd5,   // assert param_addr, input_addr (FC1 only)
    S_W_LATCH     = 4'd6,   // latch w_latch + x_latch from BRAM/regs
    S_W_ACC       = 4'd7,   // acc += w_latch * x_latch, i++
    S_SAVE        = 4'd8,   // ReLU+clip or store logit; j++
    S_NEXT_LAYER  = 4'd9,   // advance layer counter or go to argmax
    S_ARGMAX_INIT = 4'd10,  // result=0, k=1
    S_ARGMAX_CMP  = 4'd11,  // compare logits[k] vs logits[result]
    S_DONE        = 4'd12;

reg [3:0] state;

// =============================================================================
// Layer configuration (set once per layer in S_FC_INIT)
// =============================================================================
reg [1:0]  layer;       // 0=FC1, 1=FC2, 2=FC3
reg [15:0] w_base;      // weight base address in Param BRAM
reg [15:0] b_base;      // bias base address in Param BRAM
reg [9:0]  n_in;        // input width  (784 / 64 / 32)
reg [6:0]  n_out;       // output width ( 64 / 32 / 10)
reg        do_relu;     // 1 for FC1/FC2; 0 for FC3

// =============================================================================
// Loop counters and running bases (avoids multipliers)
// =============================================================================
reg [6:0]  j;           // current output neuron index
reg [9:0]  i;           // current input index
reg [15:0] w_row_base;  // = w_base + j * n_in  (updated +n_in per j)
reg [15:0] b_row_base;  // = b_base + j * 4     (updated +4 per j, INT32 biases)
reg [1:0]  bias_byte_idx; // which byte of the 4-byte INT32 bias (0=LSB, 3=MSB)

// =============================================================================
// Accumulator and pipeline latches
// =============================================================================
reg signed [31:0] acc;
reg signed [7:0]  w_latch;   // latched INT8 weight
reg signed [8:0]  x_latch;   // latched input: 9-bit signed (holds INT8)

// =============================================================================
// Activation buffers  (inter-layer values)
// =============================================================================
reg [7:0] act1 [0:63];          // FC1 output (after ReLU, clipped 0–127)
reg [7:0] act2 [0:31];          // FC2 output (after ReLU, clipped 0–127)
reg signed [31:0] logits [0:9]; // FC3 raw int32 logits

// =============================================================================
// Argmax helper
// =============================================================================
reg [3:0] argmax_k;   // index being compared in argmax loop

// =============================================================================
// ReLU + saturating clip to INT8 range [0, 127]
// Applied after FC1 and FC2 to keep activations in INT8 before next layer.
// =============================================================================
function [7:0] relu_clip;
    input signed [31:0] x;
    begin
        if (x <= 32'sd0)         relu_clip = 8'h00;
        else if (x > 32'sd127)   relu_clip = 8'h7F;
        else                     relu_clip = x[7:0];
    end
endfunction

// =============================================================================
// Main FSM
// =============================================================================
always @(posedge clk or negedge rst_n) begin : fsm
    integer ridx;

    if (!rst_n) begin
        state         <= S_IDLE;
        done          <= 1'b0;
        result        <= 4'd0;
        param_en      <= 1'b0;
        input_en      <= 1'b0;
        param_addr    <= 16'h0;
        input_addr    <= 10'h0;
        acc           <= 32'sd0;
        w_latch       <= 8'sd0;
        x_latch       <= 9'sd0;
        j             <= 7'd0;
        i             <= 10'd0;
        layer         <= 2'd0;
        bias_byte_idx <= 2'd0;
        argmax_k      <= 4'd0;
        for (ridx = 0; ridx < 10; ridx = ridx + 1)
            logits[ridx] <= 32'sd0;
    end else begin

        // Default: deassert one-cycle signals
        param_en <= 1'b0;
        input_en <= 1'b0;
        done     <= 1'b0;

        case (state)

            // ── Wait for start pulse ──────────────────────────────────────
            S_IDLE: begin
                if (start) begin
                    layer <= 2'd0;
                    state <= S_FC_INIT;
                end
            end

            // ── Load layer-specific parameters; reset output index j ─────
            S_FC_INIT: begin
                j             <= 7'd0;
                bias_byte_idx <= 2'd0;
                case (layer)
                    2'd0: begin  // FC1: 784 → 64
                        w_base     <= FC1_W_BASE;
                        b_base     <= FC1_B_BASE;
                        n_in       <= 10'd784;
                        n_out      <= 7'd64;
                        do_relu    <= 1'b1;
                        w_row_base <= FC1_W_BASE;
                        b_row_base <= FC1_B_BASE;
                    end
                    2'd1: begin  // FC2: 64 → 32
                        w_base     <= FC2_W_BASE;
                        b_base     <= FC2_B_BASE;
                        n_in       <= 10'd64;
                        n_out      <= 7'd32;
                        do_relu    <= 1'b1;
                        w_row_base <= FC2_W_BASE;
                        b_row_base <= FC2_B_BASE;
                    end
                    default: begin  // FC3: 32 → 10
                        w_base     <= FC3_W_BASE;
                        b_base     <= FC3_B_BASE;
                        n_in       <= 10'd32;
                        n_out      <= 7'd10;
                        do_relu    <= 1'b0;
                        w_row_base <= FC3_W_BASE;
                        b_row_base <= FC3_B_BASE;
                    end
                endcase
                state <= S_BIAS_ADDR;
            end

            // ── Present address of current bias byte ──────────────────────
            // All biases are INT32 (little-endian), so 4 bytes per neuron.
            // Address = b_row_base + bias_byte_idx  (b_row_base = b_base + j*4)
            S_BIAS_ADDR: begin
                param_addr <= b_row_base + {14'b0, bias_byte_idx};
                param_en   <= 1'b1;
                state      <= S_BIAS_LATCH;
            end

            // ── Wait 1 cycle for BRAM output (DO_REG=0, 1-cycle latency) ─
            S_BIAS_LATCH: begin
                state <= S_BIAS_LOAD;
            end

            // ── Shift one bias byte into the accumulator ──────────────────
            // Bytes are little-endian: byte 0 → acc[7:0], byte 3 → acc[31:24]
            // After all 4 bytes: proceed to weight MAC loop (i=0)
            S_BIAS_LOAD: begin
                case (bias_byte_idx)
                    2'd0: acc[ 7: 0] <= param_rdata;
                    2'd1: acc[15: 8] <= param_rdata;
                    2'd2: acc[23:16] <= param_rdata;
                    2'd3: acc[31:24] <= param_rdata;
                endcase

                if (bias_byte_idx == 2'd3) begin
                    bias_byte_idx <= 2'd0;
                    i             <= 10'd0;
                    state         <= S_W_ADDR;
                end else begin
                    bias_byte_idx <= bias_byte_idx + 2'd1;
                    state         <= S_BIAS_ADDR;
                end
            end

            // ── Present weight and (for FC1) input pixel addresses ────────
            // Weight byte address: w_row_base + i  (= w_base + j*n_in + i)
            // Input pixel address: i               (only for FC1)
            S_W_ADDR: begin
                param_addr <= w_row_base + i;
                param_en   <= 1'b1;
                if (layer == 2'd0) begin
                    input_addr <= i[9:0];
                    input_en   <= 1'b1;
                end
                state <= S_W_LATCH;
            end

            // ── Latch weight and input (1 cycle after BRAM address) ───────
            // param_rdata: INT8 weight  (Param BRAM, valid this cycle)
            // input:       INT8 pixel   (FC1, sign-extended from BRAM byte)
            //              INT8 act1/2  (FC2/FC3, from register arrays, 0–127)
            //
            // x_latch is 9-bit signed.
            //   FC1 input: SIGN-extend INT8 pixel → handles negative values
            //              (normalized pixels after (pixel/255-mean)/std can be
            //               small negative; e.g., a black pixel ≈ -0.42/scale ≈ -19)
            //   FC2/FC3:   ZERO-extend act (always 0–127 after ReLU+clip)
            S_W_LATCH: begin
                w_latch <= $signed(param_rdata);
                case (layer)
                    2'd0:    x_latch <= {input_rdata[7], input_rdata}; // INT8 sign-extend → -128..127
                    2'd1:    x_latch <= {1'b0, act1[i]};               // FC1 act → 0..127
                    default: x_latch <= {1'b0, act2[i]};               // FC2 act → 0..127
                endcase
                state <= S_W_ACC;
            end

            // ── Multiply-accumulate: acc += weight × input ────────────────
            // $signed(w_latch) [8-bit] × $signed(x_latch) [9-bit]
            // Product: 17-bit signed, extended to 32 bits → no overflow risk.
            // Max |term|  = 128 × 128 = 16 384
            // Max |FC1 acc| ≤ 784 × 16 384 + INT32_bias ≈ fits in INT32 ✓
            S_W_ACC: begin
                acc <= acc + ($signed(w_latch) * $signed(x_latch));
                i   <= i + 10'd1;
                if (i == n_in - 10'd1)
                    state <= S_SAVE;
                else
                    state <= S_W_ADDR;
            end

            // ── Requantize + ReLU + save output ───────────────────────────
            // FC1/FC2: act_int8 = clip(ReLU(acc_int32 >>> k), 0, 127)
            // FC3:     logit = full INT32 (bias already in accumulator scale)
            S_SAVE: begin
                if (do_relu) begin
                    case (layer)
                        2'd0:    act1[j] <= relu_clip($signed(acc) >>> FC1_REQ_SHIFT);
                        2'd1:    act2[j] <= relu_clip($signed(acc) >>> FC2_REQ_SHIFT);
                        default: ;  // unreachable (do_relu=0 for FC3)
                    endcase
                end else begin
                    logits[j] <= acc;  // FC3: full INT32 for argmax
                end

                j          <= j + 7'd1;
                w_row_base <= w_row_base + n_in;  // next row of weight matrix
                b_row_base <= b_row_base + 16'd4; // next INT32 bias (4 bytes)

                if (j == n_out - 7'd1)
                    state <= S_NEXT_LAYER;
                else
                    state <= S_BIAS_ADDR;  // next output neuron
            end

            // ── Advance to next layer or to argmax ────────────────────────
            S_NEXT_LAYER: begin
                if (layer == 2'd2)
                    state <= S_ARGMAX_INIT;
                else begin
                    layer <= layer + 2'd1;
                    state <= S_FC_INIT;
                end
            end

            // ── Initialise argmax: result=0, start comparing from k=1 ────
            S_ARGMAX_INIT: begin
                result   <= 4'd0;
                argmax_k <= 4'd1;
                state    <= S_ARGMAX_CMP;
            end

            // ── Sequential argmax over 10 logits ─────────────────────────
            S_ARGMAX_CMP: begin
                if ($signed(logits[argmax_k]) > $signed(logits[result]))
                    result <= argmax_k;
                argmax_k <= argmax_k + 4'd1;
                if (argmax_k == 4'd9)
                    state <= S_DONE;
                // else remain in S_ARGMAX_CMP
            end

            // ── Assert done for one cycle, then return to idle ────────────
            S_DONE: begin
                done  <= 1'b1;
                state <= S_IDLE;
            end

            default: state <= S_IDLE;

        endcase
    end
end

endmodule
